---
dist: trusty
language: node_js
node_js:
  - 6
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "make start-selenium 2>&1 &"
  - sleep 5
script:
  - make build
  - make test
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t ston3o/ethibox .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push ston3o/ethibox;
    fi
cache: false
branches:
  only:
    - master
