apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://rawgit.com/ston3o/ethibox/master/charts/charts/matomo/icon.png
name: matomo
version: 0.1.0
appVersion: 3.3.0
keywords:
  - Analytics
