---
replicaCount: 1
image:
  repository: ston3o/ethibox
  tag: 0.6.2
service:
  type: NodePort
  port: 4444
ingress:
  enabled: true
  hosts:
    - ethibox.local
traefik:
  imageTag: 1.5.3
  serviceType: NodePort
  ssl:
    enabled: false
    enforced: false
  acme:
    enabled: true
    email: contact@example.com
    challengeType: http-01
    staging: false
    logging: true
    persistence:
      enabled: true
  rbac:
    enabled: true
persistence:
  enabled: true
